README.md
fastlane/Fastfile
lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/create_next_snapshot_version_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/bump_version_update_changelog_create_pr_action_spec.rb
spec/actions/create_next_snapshot_version_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

This PR adds a new action to the fastlane plugin, `create_next_snapshot_version`. This action will bump the version to the next minor with a `-SNAPSHOT` version and create a PR with the changes.

Add create_next_snapshot_version action to plugin

---

README.md
fastlane/Fastfile
lib/fastlane/plugin/revenuecat_internal/actions/create_github_release_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/create_github_release_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

This PR adds a new action to the fastlane plugin, `create_github_release`. This action will create a github release with the given version number as name and tag and the contents of the CHANGELOG.latest.md file as description. It can also upload files to the release if needed.

Add create_github_release action to plugin

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/create_next_snapshot_version_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/bump_version_update_changelog_create_pr_action_spec.rb
spec/actions/create_next_snapshot_version_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

As suggested by @taquitos here: https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/pull/2#discussion_r923988972, we will now validate that the release branch does not exist before continuing with the bump action. This makes sense to ensure we don't reuse an existing branch by mistake.

Validate release branch does not exist before bumping action

---

README.md
fastlane/Fastfile
lib/fastlane/plugin/revenuecat_internal/actions/replace_text_in_files_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/replace_text_in_files_action_spec.rb
spec/actions/replace_version_number_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

https://revenuecats.atlassian.net/browse/CSDK-310
This PR adds a new action to the plugin `replace_text_in_files`. This can be used by the SDKs to automate things like replacing API keys in the project or similar tasks. Each SDK would need to implement a lane that uses this action.

Add replace_text_in_files action to plugin

---

fastlane-plugin-revenuecat_internal.gemspec
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/replace_version_number_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

During the previous PR (#6 ) I noticed that the `sed` is platform dependent (it works differently in macosx and linux) which caused issues with circleci. This PR changes the implementation to use a ruby implementation instead of a command-line based implementation, which should help with legibility and make it platform agnostic.

Improve replace_in functionality so it's not platform dependant and make it more legible

---

README.md
fastlane/Fastfile
lib/fastlane/plugin/revenuecat_internal/actions/commit_current_changes_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/replace_text_in_files_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/commit_current_changes_action_spec.rb
spec/actions/replace_text_in_files_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

Created new `commit_current_changes` action so it can be used by SDKs.
Also modified `replace_text_in_files` so it supports another parameter indicating whether new text can be empty or not.

Create commit_current_changes action

---

lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/helper/revenuecat_internal_helper_spec.rb
spec/test_files/breaking_get_commit_sha_a72c0435ecf71248f311900475e881cc07ac2eaf.json
spec/test_files/get_commit_sha_0e67cdb1c7582ce3e2fd00367acc24db6242c6d6.json

This was originally developed in https://github.com/RevenueCat/purchases-ios/pull/1769 but now we have tests and we can share across all repos 👏

Splits changelog in sections depending on label

---

lib/fastlane/plugin/revenuecat_internal/actions/create_next_snapshot_version_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/create_next_snapshot_version_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

This should help dealing with: https://revenuecats.atlassian.net/browse/SDKONCALL-84
With the plugin, I added a validation for the current branch to the action that creates the next prerelease version PR. This validation didn't exist before, and caused the issue that we see in this ticket. This PR removes that validation from that action. After this is merged, I will update the SDKs to use the new version of the plugin

Not validate current branch when creating next snapshot

---

lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/helper/revenuecat_internal_helper_spec.rb

As suggested in https://github.com/RevenueCat/purchases-ios/pull/1800#discussion_r940554346. We are changing the title level of the generated changelog sections

Change title level of generated changelog sections

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/create_next_snapshot_version_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/bump_version_update_changelog_create_pr_action_spec.rb
spec/actions/create_next_snapshot_version_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

During the latest release of flutter, we noticed a few issues with the `prepare_next_version` job:
- Checking for the existence of the bump branch in remote sometimes returned a warning, which was making the code think that the branch existed in remote, even though it didn't. This PR changes the behavior to check that the returned value of the sh command contains the branch name, so it's more accurate.
- `Actions.git_branch` is supposed to give the current branch, but it wasn't working (it was returning nothing). We use this when creating the PR so we knew the `head` branch, but since it wasn't returning anything it failed during the PR creation. This PR changes the behavior to pass the branch as a parameter since we do have this information on the caller actions.

Fixes issues during flutter next snapshot creation

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/create_next_snapshot_version_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/bump_version_update_changelog_create_pr_action_spec.rb
spec/actions/create_next_snapshot_version_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

This will prevent Danger from failing these PRs due to missing a change label.
See also https://github.com/RevenueCat/purchases-ios/pull/1810

`bump_version_update_changelog_create_pr_action` and `create_next_snapshot_version_action`: added `next_release` label

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
spec/actions/bump_version_update_changelog_create_pr_action_spec.rb

Uses `UI.interactive?` to prevent asking for branch confirmation and edit of the changelog in CI

Prevents edit_changelog and branch confirmation in CI

---

lib/fastlane/plugin/revenuecat_internal/actions/determine_next_version_using_labels_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/helper/versioning_helper_spec.rb

We need to skip automatic releases if the next release is major, so I added the type of bump as a return for the action

Returns the type of bump when determining next version

---

lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/helper/revenuecat_internal_helper_spec.rb
spec/helper/versioning_helper_spec.rb

This PR adds support for versions with prerelease modifiers when trying to bump versions automatically. Now we will support versions like `1.2.3-alpha.1`, `2.2.2-beta.3` or `3.3.3-rc.4` which will increase to the version without the prerelease modifier and add `SNAPSHOT` if needed. The regex for valid version numbers now is: `^[0-9]+.[0-9]+.[0-9]+(-(alpha|beta|rc).[0-9]+)?$`.

Support prerelease version during version increase

---

lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/helper/versioning_helper_spec.rb

`next_release` PRs shouldn't be incldued in the changelog
[CSDK-421]
[CSDK-421]: https://revenuecats.atlassian.net/browse/CSDK-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Don't include next_release in changelog

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/bump_version_update_changelog_create_pr_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

As noted in https://github.com/RevenueCat/purchases-hybrid-common/pull/209, the changelog was not being populated properly because `edit_changelog` is the function that updates the latest changelog file
[CSDK-422]
[CSDK-422]: https://revenuecats.atlassian.net/browse/CSDK-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix for changelog not being generated properly

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
spec/actions/bump_version_update_changelog_create_pr_action_spec.rb

I realized the script kept going after I just pressed "enter" with an empty version number.

`bump_version_update_changelog_create_pr_action`: validate new version is not empty

---

lib/fastlane/plugin/revenuecat_internal/actions/determine_next_version_using_labels_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/helper/versioning_helper_spec.rb
spec/test_files/get_commit_sha_1285b6df6fb756d8b31337be9dabbf3ec5c0bbfe.json
spec/test_files/get_commit_sha_7d77decbcc9098145d1efd4c2de078b6121c8906.json
spec/test_files/get_commits_since_last_release_skip_release.json

We are triggering automatic releases in purchases-hybrid-common when merging into main. We shouldn’t trigger a release if the new changes don’t need a release (like maybe changes to ci, or new releases commits)
[CSDK-423]
[CSDK-423]: https://revenuecats.atlassian.net/browse/CSDK-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Skip release if no public changes

---

lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/helper/versioning_helper_spec.rb

This should resolve: https://revenuecats.atlassian.net/browse/CSDK-437. Basically, we delete and readd the `latest` tag in android on every release. This can cause the fetch to fail with this error: 
```
[15:16:04]: Exit status of command 'git fetch --tags' was 1 instead of 0.
From github.com:RevenueCat/purchases-android
* [new tag]           4.2.1-autosyncpurchases -> 4.2.1-autosyncpurchases
* [new tag]           5.0.0-amazon.alpha.6    -> 5.0.0-amazon.alpha.6
* [new tag]           5.5.0                   -> 5.5.0
! [rejected]          amazon-latest           -> amazon-latest  (would clobber existing tag)
! [rejected]          latest                  -> latest  (would clobber existing tag)
```
By adding the `-f` flag to the fetch, this will make sure we always use remote's tags. Note …

Force fetch tags in case local tags are outdated

---

fastlane/Fastfile
lib/fastlane/plugin/revenuecat_internal/actions/create_next_snapshot_version_action.rb
spec/actions/create_next_snapshot_version_action_spec.rb

We are going to start running this action on every commit to `main` and we should skip if the current version is already a snapshot version.

CreateNextSnapshotVersionAction skips if current version is SNAPSHOT

---

README.md
lib/fastlane/plugin/revenuecat_internal/actions/create_next_snapshot_version_action.rb

Just updates the `create_next_snapshot_version` action documentation to mention the changes in #31

Updates create_next_snapshot_version action documentation

---

lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/helper/versioning_helper_spec.rb

While working on https://github.com/RevenueCat/purchases-unity/pull/153, the bugfixes section was added before the new features section. I think it makes more sense to show the new features before bugfixes.  This PR just changes the order for those sections.

Sort autogenerated changelog sections to put new features before fixes

---

lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/helper/revenuecat_internal_helper_spec.rb

I thought it would be good to set it to `core-sdk` for all created PRs from any automation

Sets reviewers for all created PRs

---

lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/helper/revenuecat_internal_helper_spec.rb

Team name has changed and automatic PRs are failing to add automatic reviewers.
This used to work when the team was `core-sdk` but now it looks like even updating it to `coresdk` fails (at least requesting reviewers using their API). It looks like GitHub might have a bug, related to name changes

Update team reviewers to coresdk

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_phc_version_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/detect_bump_type.rb
lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/actions/bump_phc_version_action_spec.rb
spec/helper/versioning_helper_spec.rb

- Adds a `minor` label if the purchases-hybrid-common bump is a minor. This minor label will be detected and will force a minor bump in the next release
- Updates title and body of PR from `Automatic release` to `Automatic bump`

Adds minor label if the purchases-hybrid-common bump is a minor

---

lib/fastlane/plugin/revenuecat_internal/helper/github_helper.rb
spec/helper/github_helper_spec.rb
spec/helper/versioning_helper_spec.rb

We should be comparing against the commit where the lane is running and not against HEAD. It's possible HEAD is actually not the commit where the lane is running at.

Use last commit instead of HEAD when comparing against last release

---

lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/helper/versioning_helper_spec.rb

I didn't use the correct markdown notation for links
(Android 5.6.6)[https://github.com/RevenueCat/purchases-android/releases/tag/5.6.6]
```
(Android 5.6.6)[https://github.com/RevenueCat/purchases-android/releases/tag/5.6.6]
```
should be :
[Android 5.6.6](https://github.com/RevenueCat/purchases-android/releases/tag/5.6.6)
```
[Android 5.6.6](https://github.com/RevenueCat/purchases-android/releases/tag/5.6.6)
```

Fix links to native releases

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_phc_version_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/create_next_snapshot_version_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/determine_next_version_using_labels_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/github_helper.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/actions/bump_phc_version_action_spec.rb
spec/actions/bump_version_update_changelog_create_pr_action_spec.rb
spec/actions/create_next_snapshot_version_action_spec.rb
spec/actions/determine_next_version_using_labels_action_spec.rb
spec/helper/github_helper_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb
spec/helper/versioning_helper_spec.rb

⚠️ This still needs new tests for when prerelease is true (currently is just passing with old tests)
Improve `fastlane bump` for prereleases
This is fixing an issue when bumping from `6.0.0-alpha.1` to `6.0.0-alpha.2`
- The generated changelog was empty which was 💥 ing the entire process
Can now run `fastlane bump is_prerelease:true`
See https://github.com/RevenueCat/purchases-android/pull/764 for results
- New `is_prerelease` option on `bump_version_update_changelog_create_pr`
- Defaults to `false` 
- Renamed `create_pr_to_main` to `create_pr`
- Added `base_branch` as a parameter
- Renamed `latest_non_prerelease_version_number` to `latest_version_number`
- Added `include_prerelease` parameter
- This is what allow for a nice changelog only between prerelease versions
- …

Improve prerelease changelog generation

---

lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/helper/revenuecat_internal_helper_spec.rb

Here's the suggested workflow in iOS for hotfixes:
```
Sometimes you might need to release a patch on a version that's not the latest. Or sometimes there might have been commits on `main` that shouldn't be released, but the latest version has a big bug. For example, let's say the last version is 4.0.0, but there's a bug on 3.9.0 that needs to be released as a 3.9.1:
1. Open a PR with the fix, merge it to `main`.
1. Jump to 3.9.0 and create a new branch `release/3.9.0`. Push this branch since it will be used as base for the PR you will open in the next steps.
1. Run `bundle exec fastlane ios bump` as you would do with any release. This will create a new PR `release/3.9.1`.
```
Unfortunately, this right now leads to
> [!] Pre populated content for changelog was empty
Because there's still …

`edit_changelog`: remove error when prepopulated changelog is empty

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_phc_version_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/create_next_snapshot_version_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/bump_phc_version_action_spec.rb
spec/actions/bump_version_update_changelog_create_pr_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

[CSDK-644](https://revenuecats.atlassian.net/browse/CSDK-644)
This will prevent updating the wrong versions when replacing in files
[CSDK-644]: https://revenuecats.atlassian.net/browse/CSDK-644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
The way it should be called now would be passing the following to the action:
```
files_with_version_number = {
'./.version' => ["{x}"],
'./pubspec.yaml' => ["version: {x}"],
'./ios/purchases_flutter.podspec' => ["s.version          = '{x}'"],
'./macos/purchases_flutter.podspec' => ["s.version          = '{x}'", "s.dependency_version     = '{x}'"],
'./ios/Classes/PurchasesFlutterPlugin.m' => ["return @\"{x}\""],
'./android/build.gradle' => ["version '{x}'"], …
```

Add pattern option to files to update

---

lib/fastlane/plugin/revenuecat_internal/actions/replace_version_number_action.rb
spec/actions/create_next_snapshot_version_action_spec.rb
spec/actions/replace_version_number_action_spec.rb

With the changes from #46 , the helper `replace_version_number` got updated to accept a hash of files instead of an array. `replace_version_number_action` depends on this helper, so the action needed to be updated. This PR updates the parameters and fixes some tests

Fix replace_version_number_action to accept a hash instead of an array of files

---

lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/helper/revenuecat_internal_helper_spec.rb

When running on CI we should reset all files instead of failing the lane if there are changes.
It's possible the Git repository gets dirty after running `npm install` or `bundle install` and the lock files get updated.

Don't ensure Git status clean when running on CI

---

lib/fastlane/plugin/revenuecat_internal/helper/github_helper.rb
lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/helper/github_helper_spec.rb
spec/helper/versioning_helper_spec.rb
spec/test_files/get_commit_sha_1625e195a117ad0435864dc8a561e6a0c6052bdf.json
spec/test_files/get_commits_since_last_release.json

This will allow PRs with this label to be grouped together instead of all inside "Other changes".
If a PR has `feat` at the same time, that gets prioritized, but a PR with something like `refactor` + `RevenueCatUI` will use this new logic.

Add support for `RevenueCatUI` label

---

lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb

This allows us to tag PRs with both `revenuecatui` and `feat`, and:
- Make a minor bump
- Tag it as `RevenueCatUI`
Before this change those changes ended up under "New Features" instead.

Prioritize `revenuecatui` over `feat`

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_phc_version_action.rb
spec/actions/bump_phc_version_action_spec.rb

We don't want to make the type of update dependent of phc anymore

Stop adding `minor` labels if minor phc update

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/replace_version_number_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/bump_version_update_changelog_create_pr_action_spec.rb
spec/actions/replace_version_number_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

When we need to make a hotfix or make a prerelease, sometimes we update the files that we shouldn't. This adds support for a new parameter on these lanes that will only be updated if the version given is posterior (in semver versions) to the latest tag and it's not a prerelease.

Support updating files on latest stable release only

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_phc_version_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/create_next_snapshot_version_action.rb
spec/actions/bump_phc_version_action_spec.rb
spec/actions/create_next_snapshot_version_action_spec.rb

In #61, I missed the new parameter in a couple of actions that were not used by the natives. This should fix those

Fix issues with some actions

---

lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/helper/revenuecat_internal_helper_spec.rb

This was causing problems when we had some prerelease for a future version shipped. In that case, we don't want to consider that one the latest.

Fix issue where we were not detecting versions as latest if there was a higher prerelease version

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_phc_version_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/create_next_snapshot_version_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/replace_version_number_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/helper/revenuecat_internal_helper_spec.rb

We noticed that the files that we were using the latest stable versions weren't being updated correctly because the "previous_version" did not match the previous version that we give to the job, since that would be the version of the latest stable version at that point in time. 
This allows that piece of substitution to work with any stable semver version instead of having to specific the previous version specifically.

ReplaceVersionNumber: Make stable version substitution work with versions not matching previous version

---

lib/fastlane/plugin/revenuecat_internal/actions/git_clone_and_push.rb
lib/fastlane/plugin/revenuecat_internal/actions/git_clone_and_push_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/git_clone_and_push_action_spec.rb

Use fastlane to sync the iOS repo to its SPM variant. This is used by the changes made in this [purchases-ios PR](https://github.com/RevenueCat/purchases-ios/pull/3926).

Sync to spm repo

---

lib/fastlane/plugin/revenuecat_internal/actions/update_hybrids_versions_file_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/update_hybrids_versions_file_helper.rb
spec/actions/update_hybrids_versions_file_action_spec.rb

To make it easier to navigate, we want to add links to the releases in the `VERSIONS.md` file of the hybrids + what version of the billing client it uses. This PR adds both of those, so it also auto-migrates existing VERSIONS.md files with the new column
After merging this, we need to fix the `purchases-unity` job since that one already has an extra column. Just updating the `VERSIONS.md` to have the new column should be enough.

Add links to versions and billing client in hybrid VERSIONS.md

---

lib/fastlane/plugin/revenuecat_internal/actions/bump_phc_version_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/create_next_snapshot_version_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/github_helper.rb
lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/actions/bump_phc_version_action_spec.rb
spec/actions/bump_version_update_changelog_create_pr_action_spec.rb
spec/actions/create_next_snapshot_version_action_spec.rb
spec/test_files/breaking_get_commit_sha_a72c0435ecf71248f311900475e881cc07ac2eaf.json
spec/test_files/get_commit_sha_0e67cdb1c7582ce3e2fd00367acc24db6242c6d6.json
spec/test_files/get_commit_sha_1285b6df6fb756d8b31337be9dabbf3ec5c0bbfe.json
spec/test_files/get_commit_sha_1625e195a117ad0435864dc8a561e6a0c6052bdf.json
spec/test_files/get_commit_sha_32320acc1d6afae30a965d7add32700313123431.json
spec/test_files/get_commit_sha_5920c32646f918a2484da8aa38ccc5e9337cc449.json
spec/test_files/get_commit_sha_6d37c766b6da55dcab67c201c93ba3d4ca538e55.json
spec/test_files/get_commit_sha_75763d3f1604aa5d633e70e46299b1f2813cb163.json
spec/test_files/get_commit_sha_7d77decbcc9098145d1efd4c2de078b6121c8906.json
spec/test_files/get_commit_sha_819dc620db5608fb952c852038a3560554161707.json
spec/test_files/get_commit_sha_9237147947bcbce00f36ae3ab51acccc54690782.json
spec/test_files/get_commit_sha_9a289e554fe384e6987b086fad047671058cf044.json
spec/test_files/get_commit_sha_a72c0435ecf71248f311900475e881cc07ac2eaf.json
spec/test_files/get_commit_sha_cfdd80f73d8c91121313d72227b4cbe283b57c1e.json
spec/test_files/minor_get_commit_sha_a72c0435ecf71248f311900475e881cc07ac2eaf.json

We are going to add `pr:` as a prefix for Pull Request labels. This PR adds support for both versions, while we transition all repos to use `pr:` labels

Add support for labels with `pr:` prefix

---

lib/fastlane/plugin/revenuecat_internal/helper/github_helper.rb
lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/helper/versioning_helper_spec.rb
spec/test_files/get_commit_sha_1625e195a117ad0435864dc8a561e6a0c6052bdf.json
spec/test_files/get_commit_sha_2625e195a117ad0435864dc8a561e6a0c6052bda.json
spec/test_files/get_commit_sha_3625e195a117ad0435864dc8a561e6a0c6052bdf.json
spec/test_files/get_commit_sha_4625e195a117ad0435864dc8a561e6a0c6052bdd.json
spec/test_files/get_commit_sha_5625e195a117ad0435864dc8a561e6a0c6052bda.json
spec/test_files/get_commit_sha_6d37c766b6da55dcab67c201c93ba3d4ca538e55.json
spec/test_files/get_commit_sha_819dc620db5608fb952c852038a3560554161707.json
spec/test_files/get_commit_sha_9a289e554fe384e6987b086fad047671058cf044.json
spec/test_files/get_commits_since_last_release.json
spec/test_files/get_commits_since_last_release_features.json
spec/test_files/get_commits_since_last_release_wip.json
spec/test_files/minor_get_commit_sha_a72c0435ecf71248f311900475e881cc07ac2eaf.json

- The changelog is now split between `RevenueCat SDK` and `RevenueCatUI SDK`. Something tagged with `pr:revenuecatui` will go into the `RevenueCatUI` section
- There can be arbitrary feature labels now. For example prs with labels `feat:Customer Center` or `feat:Paywall Components` will be rendered under new sections.
- These new feature sections have subsections for fixes and new features. So a PR should still be tagged with the `pr:` label (for example `feat:Customer Center` and `pr:fix`. If the PR label is not `pr:feat` or `pr:fix` go directly to `Other changes` section (outside of the specific functionality). This is to keep “internal” features in `Other changes`, making the changelog more readable for developers
- I unified the labels: `pr:docs`, `pr:perf` to `pr:fix`. And …

Add features sections to changelog and emojis

---

lib/fastlane/plugin/revenuecat_internal/helper/github_helper.rb
spec/helper/versioning_helper_spec.rb
spec/test_files/patch_get_commit_sha_a72c0435ecf71248f311900475e881cc07ac2eaf.json

As the title says. I noticed that `pr:force_minor` wasn't working in https://github.com/RevenueCat/purchases-kmp/pull/219#issuecomment-2376221971. 
Added tests to verify `pr:force_minor` and `pr:force_patch`. The fix was to add those labels to `SUPPORTED_PR_LABELS`.

Fixes bump detection for pr:force_patch and pr:force_minor

---

lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/test_files/VERSIONS.md

This broke in #66. We should parse markdown links for the releases correctly after this change.

Fix changelog generation for hybrids to include native release links

---

lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/helper/versioning_helper_spec.rb

From some tests, the `author` field in the Github response is null on commits that were merged without a PR. This was causing the automation to fail with a 
```
versioning_helper.rb:113:in `block in auto_generate_changelog': \e[31m[!] undefined method `[]' for nil:NilClass\e[0m (NoMethodError)
``` 
error.
I didn't see another way to get the username, so I just removed it from the changelog for now

Fix changelog generation when there are commits without PRs

---

lib/fastlane/plugin/revenuecat_internal/actions/pod_push_with_error_handling.rb
spec/actions/pod_push_with_error_handling.rb
spec/actions/pod_push_with_error_handling_action_spec.rb

This adds an action that takes into account duplicate pods. 
Next step would be to add a retry if it fails due to timeouts.
In the main Fastfile, instead of adding `pod_push` we should call `pod_push_with_error_handling(path: "RevenueCat.podspec")`
Example output:
```
[14:36:17]: ------------------------------
[14:36:17]: --- Step: default_platform ---
[14:36:17]: ------------------------------
[14:36:17]: Driving the lane 'ios push_revenuecat_pod' 🚀
[14:36:17]: -----------------------------
[14:36:17]: --- Step: setup_circle_ci ---
[14:36:17]: -----------------------------
[14:36:17]: Not running on CI, skipping CI setup
[14:36:17]: ------------------------------------------
[14:36:17]: --- Step: pod_push_with_error_handling ---
[14:36:17]: ------------------------------------------ …
```

feat: add duplicate handling

---

fastlane-plugin-revenuecat_internal.gemspec
fastlane/Fastfile
lib/fastlane/plugin/revenuecat_internal/actions/scan_with_flaky_test_retries.rb

The full retry of `scan` with only failed tests was retrying sometimes when it shouldn't. It was detecting failurs when tests were retried within Xcode that eventually succeeded.
Only writing failed tests if they don't have a successful run in the suite (this means they did eventually pass)
| Failure | Successful retry |
|--------|--------|
| <img width="1412" alt="Screenshot 2025-04-18 at 1 53 53 PM" src="https://github.com/user-attachments/assets/972faf48-9d5a-432f-b0f9-142dff3c8cd2" /> | <img width="1197" alt="Screenshot 2025-04-18 at 1 54 13 PM" src="https://github.com/user-attachments/assets/0f23383a-4d30-4090-93f6-ac75da8d5f17" /> |

Only retry tests that failed but didn't succeed after in-run retry

---

lib/fastlane/plugin/revenuecat_internal/actions/commit_all_changes_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/create_or_checkout_branch_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/create_pr_if_necessary_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/actions/commit_all_changes_action_spec.rb
spec/actions/create_or_checkout_branch_action_spec.rb
spec/actions/create_pr_if_necessary_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb

Adds some utilities used in https://github.com/RevenueCat/purchases-android/pull/2365
- `create_or_checkout_branch` 
- `commit_all_changes` (didn't want to adjust `commit_current_changes` because [it is widely used](https://github.com/search?q=org%3ARevenueCat%20%22commit_current_changes%22&type=code)) 
- `create_pr_if_necessary`

Adds `create_or_checkout_branch`, `commit_all_changes`, `create_pr_if_necessary`

---

fastlane/Fastfile
lib/fastlane/plugin/revenuecat_internal/actions/bump_version_update_changelog_create_pr_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/check_github_authentication_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/create_github_release_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/determine_next_version_using_labels_action.rb
spec/actions/check_github_authentication_action_spec.rb

We were referencing `RC_INTERNAL_GITHUB_TOKEN` in a bunch of lanes, and it is not set in any repository. Repositories have `GITHUB_TOKEN` set though, so replacing it with that one.
I still think we should probably unify and remove `GITHUB_PULL_REQUEST_API_TOKEN` as well, since I can't think of a reason why we would need changelog generation and PR tokens to be different

Use correct `GITHUB_TOKEN`

---

lib/fastlane/plugin/revenuecat_internal/actions/get_latest_github_release_within_same_major_action.rb
lib/fastlane/plugin/revenuecat_internal/actions/update_hybrids_versions_file_action.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
lib/fastlane/plugin/revenuecat_internal/helper/update_hybrids_versions_file_helper.rb
lib/fastlane/plugin/revenuecat_internal/helper/versioning_helper.rb
spec/actions/get_latest_github_release_witin_same_major_action_spec.rb
spec/actions/update_hybrids_versions_file_action_spec.rb
spec/helper/revenuecat_internal_helper_spec.rb
spec/helper/update_hybrids_versions_file_helper_spec.rb
spec/helper/versioning_helper_spec.rb

`GetLatestGithubReleaseWithinSameMajorAction ` and `UpdateHybridsVersionsFileAction` were using unauthenticated GitHub requests

Add missing GitHub auth in some actions

---

lib/fastlane/plugin/revenuecat_internal/helper/github_helper.rb
lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
lib/fastlane/plugin/revenuecat_internal/helper/update_hybrids_versions_file_helper.rb
spec/helper/github_helper_spec.rb

We believe we are getting secondary rate limits (https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits)
Example: https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/30452/workflows/5f7c7b67-0a74-4e9b-85c1-d69109552247/jobs/381378
This PR adds a retry mechanism

Add retries when hitting secondary rate limits 

---

lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
lib/fastlane/plugin/revenuecat_internal/helper/update_hybrids_versions_file_helper.rb

After removing the default value of `nil` for a `github_token` parameter in #90, the whole plugin started to fail. This PR brings back the `= nil` default value
Example of successful execution with this change: https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/30467/workflows/df189710-56b6-47ec-b8fd-19129b69d392

Bring back `nil` as default value for parameters to fix plugin

---

lib/fastlane/plugin/revenuecat_internal/helper/revenuecat_internal_helper.rb
spec/helper/revenuecat_internal_helper_spec.rb

Follow up of #89 
Fixes formatting by only appending one newline when inserting CHANGELOG.latest.md into `main`'s CHANGELOG.md. The reason for this change is that our CHANGELOG.latest.md files already end with a newline `\n`, so we only need to append 1 newline instead of 2 to have the correct formatting (the correct separation with the previous version changelog)
<details>
<summary>Before this PR (notice the extra newline before "## 6.2.13")</summary>
```
The changelog diff would be:
diff --git a/CHANGELOG.md b/CHANGELOG.md
index fe20e6b..a92595f 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -140,6 +140,23 @@ Using the SDK with your own IAP code is still supported in v7. Other than updati
* Bump danger from 9.5.1 to 9.5.3 (#687) via dependabot[bot]
(@dependabot[bot]) via RevenueCat Git …
```

nit: add only one newline when inserting changelog latest

---

lib/fastlane/plugin/revenuecat_internal/actions/insert_changelog_of_older_version_action.rb
spec/actions/insert_changelog_of_older_version_action_spec.rb

Follow up of #89 and enabled by #95 
Use `pr:changelog_ignore` label for the PRs that update the changelog of `main` from releases of previous majors.

Use `pr:changelog_ignore` for old-major-changelog update PRs
